FROM python:3.7.3


WORKDIR /app
RUN mkdir /app/airquality

COPY requirements.txt /app/airquality/requirements.txt
RUN pip install -r /app/airquality/requirements.txt

COPY . /app/airquality/

RUN echo "FLASK_APP=airquality" >> /app/.env
RUN echo "FLASK_ENV=development" >> /app/.env
CMD  flask run --host 0.0.0.0