DROP TABLE IF EXISTS readings;
DROP TABLE IF EXISTS devices;

CREATE TABLE readings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	device_id 
	pmi25 NUMERIC NOT NULL,
	pmi10 NUMERIC NOT NULL
);

