FROM python:3.7.3


WORKDIR /app
RUN mkdir /app/app/

COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY app/ /app/app/
COPY run.py /app/

RUN mkdir /app/build
COPY build/ /app/build

RUN echo "FLASK_APP=run.py" >> /app/.env
RUN echo "FLASK_ENV=development" >> /app/.env
CMD flask run --host 0.0.0.0
